name: CI-tests

on:
  push:
    branches: [ master, lifelong ]
  pull_request:
    branches: [ master, lifelong ]

# cancel the previous run in the PR (only PR) if it's still in progress
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.sha }}
  cancel-in-progress: true

jobs:
  run_unit_tests:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: 18
          cache: maven
      - name: Check mvn version
        run: mvn -version

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true -Djunit.jupiter.execution.parallel.mode.classes.default=same_thread -Dtest=%regex[.*(?!.*(?:StressTest|LifelongSolverFactoryTest)).*Test.*] test
  test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
  run_LL_factory_regression_test:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 18
          cache: maven
      - name: Check mvn version
        run: mvn -version

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true -Djunit.jupiter.execution.parallel.mode.classes.default=same_thread -Dtest=LifelongSolverFactoryTest test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Lifelong Factory Regression Test
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true