name: CI-tests

on:
  push:
    branches: [ master, lifelong ]
  pull_request:
    branches: [ master, lifelong ]

jobs:
  run_unit_tests:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' 
          java-version: 18
          cache: maven
      - name: Check mvn version
        run: mvn -version

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true -Dmaven.test.skip=true -Dtest=!StressTest test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Unit Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
  run_stress_tests:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v3
      - name: Set up JDK 18
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 18
          cache: maven
      - name: Check mvn version
        run: mvn -version

      - name: Build
        run: mvn --batch-mode -DskipTests package

      - name: Test
        run: mvn --batch-mode -Dmaven.test.failure.ignore=true -Dmaven.test.skip=false -Dtest=StressTest test

      - name: Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Stress Tests
          path: target/surefire-reports/*.xml
          reporter: java-junit
          fail-on-error: true
